### ISSUE TITLE
How to have this on linux?

### ISSUE THREAD

**Issue by emmggi** [Lex98/py_win_keyboard_layout#1]
How does one have this on linux? I can't get it to work in IDLE and pywin32 isn't available on linux as far as I know. Each time I try to run the list command I get an error in IDLE.

Importing:
```python
>>> import py_win_keyboard_layout
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hex/Documents/scripts/py_win_keyboard_layout/py_win_keyboard_layout/__init__.py", line 6, in <module>
    import win32gui
ModuleNotFoundError: No module named 'win32gui'
```
Trying to install win32gui:
```bash
Collecting win32gui
  Downloading https://files.pythonhosted.org/packages/b8/75/7bed82934e51903f9d48b26b3996161bb2dce1731607b4bb7fd26003ed3e/win32gui-221.5.tar.gz (605kB)
    100% |████████████████████████████████| 614kB 970kB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y043h1b6/win32gui/setup.py", line 27, in <module>
        from win32.distutils.gui import win32gui_build_ext
      File "/tmp/pip-install-y043h1b6/win32gui/win32/distutils/gui.py", line 4, in <module>
        import winreg
    ModuleNotFoundError: No module named 'winreg'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-y043h1b6/win32gui/
```
winreg:
```bash
Collecting winreg
  Could not find a version that satisfies the requirement winreg (from versions: )
No matching distribution found for winreg
```

Trying to use it:
```python
Python 3.7.1 (default, Oct 22 2018, 10:41:28) 
[GCC 8.2.1 20180831] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> py_win_keyboard_layout.get_keyboard_layout_list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'py_win_keyboard_layout' is not defined
```

**Comment by Lex98** [comment]
Unfortunately it can be used only on windows.

**Comment by emmggi** [comment]
Any alternative to switch keyboard layouts on windows AND linux that you know of?
